server:
  port: 8071
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #版本看自己数据库版本安装
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&userSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  cloud:
    nacos: #nacos配置
      discovery:
        server-addr: localhost:8848
rocketmq:
  name -server: 122.9.161.37:9876 #RocketMQ的name-server的地址