server:
  port: 8091
spring:
  application:
    name: service-order
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false #让nacos把它当成一个url不要做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&userSSL=true
    username: root
    password: 123456
  jap:
    hibernate:
      hb2ddl:
        auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBialect
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999 #跟控制台交流端口，随意一个未使用的端口
        dashboard: localhost：8080 #指定控制台的服务地址
#      filter:
#        enabled: false#之前版本需要这样这是加上Filetercontext
      web-context-unify: false # 关闭context整合链路控制
service-product: #服务提供者的名称
  ribbon:
   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启fegin对sentinel支持
feign:
  sentinel:
    enabled: true
#rocketMQ
rocketmq:
  name-server:  192.168.109.131：9876  #rocketMQ服务地址
  producer:
    group: shop-order  #生产者组